spring.application.name=application-name
spring.datasource.url=jdbc:mysql://localhost:0000/db_name
spring.datasource.username=your_username
spring.datasource.password=your_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=your_secret_key
logging.level.root=WARN
logging.level.org.springframework=ERROR
logging.level.org.hibernate=ERROR
app.frontend-base-url=http://localhost:3000
app.mail.from=no-reply@example.com
spring.mail.host=smtp.example.com
spring.mail.port=587
spring.mail.username=your_smtp_username
spring.mail.password=your_smtp_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.default-tenant-id=1
app.seed.default-admin.enabled=false
app.seed.default-admin.name=Default Admin
app.seed.default-admin.email=admin@example.com
app.seed.default-admin.password=change-me
